# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@v4

            # Set up Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            # Install dependencies
            - name: Install dependencies
              run: yarn install

            # Build Nuxt
            - name: Build Nuxt
              run: yarn build

            # Copy sitemap tĩnh vào public folder
            - name: Copy sitemap to public folder
              run: |
                  mkdir -p ./.output/public
                  cp sitemap.xml ./.output/public/sitemap.xml

            # Upload artifact cho GitHub Pages
            - name: Upload artifact for Pages
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./.output/public

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
